services:
  data_analytics:
    build:
      context: dashboard  # Only send this folder to Docker
      dockerfile: Dockerfile
    entrypoint: ["streamlit", "run", "app/main.py", "--server.port=4200", "--server.address=0.0.0.0"]
    tty: true
    restart: unless-stopped
    environment:
      environment: "local"
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    ports:
      - "4200:4200"
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync+restart
          path: dashboard
          target: /dashboard
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
